{% set name = "tidy-viewer" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alexhallam/tv/archive/{{ version }}.tar.gz
  sha256: a1d58603d4c211f5315def822ed73a0fdf7e24430aa5b4bb2e8c6baeaf28c4ee

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - tidy-viewer 2>&1 | grep -q "No such file or directory"  # [linux and x86_64]
    - tidy-viewer 2>&1 | grep -q "Inappropriate ioctl for device"  # [linux and aarch4]
    - tidy-viewer 2>&1 | grep -q "Inappropriate ioctl for device"  # [linux and ppc64le]
    - tidy-viewer 2>&1 | grep -q "Resource temporarily unavailable"  # [osx]
    - start /b tidy-viewer   # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]
    - taskkill /F /im tidy-viewer.exe  # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]

about:
  home: https://github.com/alexhallam/tv
  license: Unlicense
  license_file:
    - UNLICENSE
    - THIRDPARTY.yml
  summary: Tidy Viewer is a cross-platform CLI csv pretty printer that uses column styling to maximize viewer enjoyment
  dev_url: https://github.com/alexhallam/tv

extra:
  recipe-maintainers:
    - danielnachun
